name: CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Frontend Syntax Check
      working-directory: ./client
      run: |
        find . -name "*.js" -exec node --check {} +

    - name: Backend Syntax Check
      working-directory: ./api
      run: |
        find . -name "*.js" -exec node --check {} +

    