name: CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run ESLint on Frontend
      working-directory: ./client
      run: |
        npm install --save-dev eslint@8 eslint-plugin-react
        echo '{
        "env": {
            "browser": true,
            "es2021": true,
            "jest": true
        },
        "extends": ["eslint:recommended", "plugin:react/recommended"],
        "parserOptions": {
            "ecmaFeatures": { "jsx": true },
            "ecmaVersion": 12,
            "sourceType": "module"
        },
        "plugins": ["react"],
        "rules": {
            "react/prop-types": "off"
        },
        "settings": {
            "react": {
            "version": "detect"
            }
        }
        }' > .eslintrc.json
        npx eslint . --ext .js,.jsx || true

    - name: Run ESLint on Backend
      working-directory: ./api
      run: |
        npm install --save-dev eslint@8 eslint-plugin-react
        echo '{
        "env": {
            "browser": true,
            "es2021": true,
            "jest": true
        },
        "extends": ["eslint:recommended", "plugin:react/recommended"],
        "parserOptions": {
            "ecmaFeatures": { "jsx": true },
            "ecmaVersion": 12,
            "sourceType": "module"
        },
        "plugins": ["react"],
        "rules": {
            "react/prop-types": "off"
        },
        "settings": {
            "react": {
            "version": "detect"
            }
        }
        }' > .eslintrc.json
        npx eslint . --ext .js,.jsx || true    
    
    - name: Run SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=DevSecOpsBootStrap \
          -Dsonar.projectName=DevSecOpsBootStrap \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN \
         
        